// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: TFT160x128

#ifndef _TFT160X128_UI_H
#define _TFT160X128_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_MainScreen.h"
#include "ui_MessScreen.h"
#include "ui_HelpScreen.h"
#include "ui_ConversationScreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(
    ui_img_chat_24dp_000000_fill0_wght300_grad0_opsz24_png);    // assets/chat_24dp_000000_FILL0_wght300_GRAD0_opsz24.png
LV_IMG_DECLARE(
    ui_img_help_24dp_000000_fill0_wght300_grad0_opsz24_png);    // assets/help_24dp_000000_FILL0_wght300_GRAD0_opsz24.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
