// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: TFT160x128

#ifndef _UI_COMP_CONVERSATION_H
#define _UI_COMP_CONVERSATION_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Conversation
#define UI_COMP_CONVERSATION_CONVERSATION 0
#define UI_COMP_CONVERSATION_IDCONVERSATION 1
#define _UI_COMP_CONVERSATION_NUM 2
lv_obj_t * ui_Conversation_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
