// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: TFT160x128

#ifndef _TFT160X128_UI_COMP_HOOK_H
#define _TFT160X128_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_BubbleChat_create_hook(lv_obj_t * comp);
void ui_comp_Conversation_create_hook(lv_obj_t * comp);
void ui_comp_IDconversation_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
