// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: TFT160x128

#include "ui.h"
#include <WiFi.h>
#include <HTTPClient.h>


lv_obj_t * uic_ConversationScreen;
lv_obj_t * ui_ConversationScreen = NULL;
lv_obj_t * ui_InputChatArea = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_BubbleChat[20] = NULL;
// event funtions
void ui_event_InputChatArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_ENTER) {
        CreatBubbleChat(e);
    }
}

// build funtions

void ui_ConversationScreen_screen_init(void)
{
    ui_ConversationScreen = lv_obj_create(NULL);
    lv_obj_set_flex_flow(ui_ConversationScreen, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_ConversationScreen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_InputChatArea = lv_textarea_create(ui_ConversationScreen);
    lv_obj_set_width(ui_InputChatArea, 158);
    lv_obj_set_height(ui_InputChatArea, LV_SIZE_CONTENT);    /// 26
    lv_obj_set_x(ui_InputChatArea, 181);
    lv_obj_set_y(ui_InputChatArea, 258);
    lv_obj_set_align(ui_InputChatArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_InputChatArea, "Chat here");
    lv_textarea_set_one_line(ui_InputChatArea, true);
    lv_obj_clear_flag(ui_InputChatArea, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_InputChatArea, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_InputChatArea, lv_color_hex(0x35BEC3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_InputChatArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_InputChatArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_InputChatArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_ConversationScreen);
    lv_obj_set_width(ui_Panel5, 158);
    lv_obj_set_height(ui_Panel5, 84);
    lv_obj_set_x(ui_Panel5, 0);
    lv_obj_set_y(ui_Panel5, -24);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel5, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Panel5, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Panel5, LV_OBJ_FLAG_SCROLL_WITH_ARROW);     /// Flags

    ui_BubbleChat1 = ui_BubbleChat_create(ui_Panel5);
    lv_obj_set_x(ui_BubbleChat1, -153);
    lv_obj_set_y(ui_BubbleChat1, -26);

    ui_BubbleChat3 = ui_BubbleChat_create(ui_Panel5);
    lv_obj_set_x(ui_BubbleChat3, -153);
    lv_obj_set_y(ui_BubbleChat3, -26);

    ui_BubbleChat4 = ui_BubbleChat_create(ui_Panel5);
    lv_obj_set_x(ui_BubbleChat4, -153);
    lv_obj_set_y(ui_BubbleChat4, -26);

    ui_BubbleChat5 = ui_BubbleChat_create(ui_Panel5);
    lv_obj_set_x(ui_BubbleChat5, -153);
    lv_obj_set_y(ui_BubbleChat5, -26);

    ui_BubbleChat6 = ui_BubbleChat_create(ui_Panel5);
    lv_obj_set_x(ui_BubbleChat6, -153);
    lv_obj_set_y(ui_BubbleChat6, -26);

    lv_obj_add_event_cb(ui_InputChatArea, ui_event_InputChatArea, LV_EVENT_ALL, NULL);
    uic_ConversationScreen = ui_ConversationScreen;

}

void ui_ConversationScreen_screen_destroy(void)
{
    if(ui_ConversationScreen) lv_obj_del(ui_ConversationScreen);

    // NULL screen variables
    uic_ConversationScreen = NULL;
    ui_ConversationScreen = NULL;
    ui_InputChatArea = NULL;
    ui_Panel5 = NULL;
    ui_BubbleChat1 = NULL;
    ui_BubbleChat3 = NULL;
    ui_BubbleChat4 = NULL;
    ui_BubbleChat5 = NULL;
    ui_BubbleChat6 = NULL;

}

// Function to create a chat bubble
lv_obj_t * ui_BubbleChat_create(lv_obj_t * parent) {
    lv_obj_t * bubble = lv_obj_create(parent);
    lv_obj_set_width(bubble, 150);
    lv_obj_set_height(bubble, 50);
    lv_obj_set_style_bg_color(bubble, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(bubble, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(bubble, lv_color_hex(0x35BEC3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(bubble, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(bubble, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(bubble, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(bubble, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(bubble, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(bubble, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(bubble, 255, LV_PART_MAIN | LV_STATE_DEFAULT);      
    lv_obj_set_style_bg_grad_color(bubble, lv_color_hex(0x73EADE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(bubble, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(bubble, true, LV_PART_MAIN | LV_STATE_DEFAULT);    
    lv_obj_t * label = lv_label_create(bubble);
    lv_label_set_text(label, "Chat message here");
    lv_obj_set_width(label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(label, LV_ALIGN_CENTER);
    lv_obj_add_flag(label, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(label, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    return bubble;
}  

void CreatBubbleChat(lv_event_t * e) {
    const char *msg_text = lv_textarea_get_text(ui_InputChatArea);

    if (strlen(msg_text) == 0) return; // Không gửi tin trống

    lv_obj_t * bubble = ui_BubbleChat_create(ui_Panel5);

    // Thiết lập lại vị trí (tuỳ chỉnh theo vị trí cuối cùng)
    lv_obj_set_x(bubble, 10); // ví dụ căn trái nếu là tin từ đối phương
    lv_obj_set_y(bubble, -26);

    // Cập nhật nội dung
    lv_obj_t * label = lv_obj_get_child(bubble, 0);  // label là con đầu tiên
    lv_label_set_text(label, msg_text);

    // Làm nổi bật nếu là tin của "tôi"
    lv_obj_set_style_bg_color(bubble, lv_color_hex(0xA6E1F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_align(bubble, LV_ALIGN_RIGHT_MID, 0); // căn phải

    // Gửi tin sang thiết bị khác
    sendMessageToOtherDevice(msg_text);

    // Xoá khung nhập
    lv_textarea_set_text(ui_InputChatArea, "");
}

// Event function for input chat area
void ui_event_InputChatArea(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_KEY && lv_event_get_key(e) == LV_KEY_ENTER) {
        CreatBubbleChat(e);
    }
}
// Event function for bubble chat
void ui_event_BubbleChat(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        // Handle click event for bubble chat
        lv_obj_t * bubble = lv_event_get_target(e);
        // Do something with the bubble object
        // For example, you can change its style or text
        lv_label_set_text(lv_obj_get_child(bubble, 0), "Clicked!");
    }
}
/*
void sendMessageToOtherDevice(const char *message) {
    while (WiFi.status() != WL_CONNECTED) {
        delay(500);
        Serial.print("Not connected\n");
    }
    //send message to other device
    HTTPClient http;
    http.begin("http://<other_device_ip>/send_message"); // Replace with the actual IP address of the other device
    http.addHeader("Content-Type", "application/json");
}
    
void sendMessage(String content) {
  if (WiFi.status() == WL_CONNECTED) {
    HTTPClient http;
    http.begin(serverSend);
    http.addHeader("Content-Type", "application/json");
    String jsonData = "{\"sender_id\":\"" + deviceId + "\",\"receiver_id\":\"" + receiverId + "\",\"content\":\"" + content + "\"}";
    int httpResponseCode = http.POST(jsonData);
    Serial.print("Da gui: ");
    Serial.println(content);
    http.end();
  }
}
*/

/*
// Function to create a conversation
lv_obj_t * ui_Conversation_create(lv_obj_t * parent) {
    lv_obj_t * conversation = lv_obj_create(parent);
    lv_obj_set_width(conversation, 150);
    lv_obj_set_height(conversation, 50);
    lv_obj_set_style_bg_color(conversation, lv_color_hex(0xFFFFFF), LV          _PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(conversation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(conversation, lv_color_hex(0x35BEC3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(conversation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(conversation, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(conversation, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(conversation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(conversation, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(conversation, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(conversation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);      
    lv_obj_set_style_bg_grad_color(conversation, lv_color_hex(0x73EADE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(conversation, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(conversation, true, LV_PART_MAIN | LV_STATE_DEFAULT);    
    lv_obj_t * label = lv_label_create(conversation);
    lv_label_set_text(label, "Conversation here");
    lv_obj_set_width(label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(label, LV_ALIGN_CENTER);
    lv_obj_add_flag(label, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(label, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    return conversation;
}

// Function to create a conversation with a specific ID
lv_obj_t * ui_Conversation_create_with_id(lv_obj_t * parent, const char * id) {
    lv_obj_t * conversation = ui_Conversation_create(parent);
    lv_obj_t * label = lv_label_create(conversation);
    lv_label_set_text(label, id);
    lv_obj_set_width(label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(label, LV_ALIGN_CENTER);
    lv_obj_add_flag(label, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(label, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    return conversation;
}
// Event function for conversation
void ui_event_Conversation_Conversation(lv_event_t * e) {   
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        // Handle click event for conversation
        lv_obj_t * conversation = lv_event_get_target(e);
        // Do something with the conversation object
        // For example, you can change its style or text
        lv_label_set_text(lv_obj_get_child(conversation, 0), "Clicked!");
    }
}
    */