// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: TFT160x128

#include "ui.h"

// COMPONENT BubbleChat

lv_obj_t * ui_BubbleChat_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_BubbleChat;
    cui_BubbleChat = lv_textarea_create(comp_parent);
    lv_obj_set_width(cui_BubbleChat, 137);
    lv_obj_set_height(cui_BubbleChat, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(cui_BubbleChat, -153);
    lv_obj_set_y(cui_BubbleChat, -27);
    lv_obj_set_align(cui_BubbleChat, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(cui_BubbleChat, 54);
    lv_textarea_set_placeholder_text(cui_BubbleChat, "Bubble Chat");
    lv_textarea_set_one_line(cui_BubbleChat, true);
    lv_obj_set_style_text_color(cui_BubbleChat, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_BubbleChat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_BubbleChat, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(cui_BubbleChat, lv_color_hex(0x99E3F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(cui_BubbleChat, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BUBBLECHAT_NUM);
    children[UI_COMP_BUBBLECHAT_BUBBLECHAT] = cui_BubbleChat;
    lv_obj_add_event_cb(cui_BubbleChat, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_BubbleChat, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_BubbleChat_create_hook(cui_BubbleChat);
    return cui_BubbleChat;
}

