// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: TFT160x128

#include "ui.h"

// COMPONENT IDconversation

lv_obj_t * ui_IDconversation_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_IDconversation;
    cui_IDconversation = lv_textarea_create(comp_parent);
    lv_obj_set_width(cui_IDconversation, 71);
    lv_obj_set_height(cui_IDconversation, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_IDconversation, -40);
    lv_obj_set_y(cui_IDconversation, 0);
    lv_obj_set_align(cui_IDconversation, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(cui_IDconversation, 52);
    lv_textarea_set_placeholder_text(cui_IDconversation, "ID");
    lv_textarea_set_one_line(cui_IDconversation, true);
    lv_obj_add_state(cui_IDconversation, LV_STATE_CHECKED);       /// States
    lv_obj_clear_flag(cui_IDconversation, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_text_font(cui_IDconversation, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_IDCONVERSATION_NUM);
    children[UI_COMP_IDCONVERSATION_IDCONVERSATION] = cui_IDconversation;
    lv_obj_add_event_cb(cui_IDconversation, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_IDconversation, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_IDconversation_create_hook(cui_IDconversation);
    return cui_IDconversation;
}

