// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: TFT160x128

#ifndef _UI_COMP_BUBBLECHAT_H
#define _UI_COMP_BUBBLECHAT_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT BubbleChat
#define UI_COMP_BUBBLECHAT_BUBBLECHAT 0
#define _UI_COMP_BUBBLECHAT_NUM 1
lv_obj_t * ui_BubbleChat_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
