// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: TFT160x128

#ifndef UI_CONVERSATIONSCREEN_H
#define UI_CONVERSATIONSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ConversationScreen
extern void ui_ConversationScreen_screen_init(void);
extern void ui_ConversationScreen_screen_destroy(void);
extern lv_obj_t * ui_ConversationScreen;
extern void ui_event_InputChatArea(lv_event_t * e);
extern lv_obj_t * ui_InputChatArea;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_BubbleChat[20];

// CUSTOM VARIABLES
extern lv_obj_t * uic_ConversationScreen;



#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

