// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: TFT160x128

#include "ui.h"

void ui_comp_BubbleChat_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Conversation_create_hook(lv_obj_t * comp)
{
}

void ui_comp_IDconversation_create_hook(lv_obj_t * comp)
{
}
