// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: TFT160x128

#include "ui.h"

void CheckIDinDB(lv_event_t * e)
{
	// Your code here
}

void CreatBubbleChat(lv_event_t * e)
{
	// Your code here
}
