// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: TFT160x128

#include "ui.h"

lv_obj_t * ui_HelpScreen = NULL;
// event funtions

// build funtions

void ui_HelpScreen_screen_init(void)
{
    ui_HelpScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HelpScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_HelpScreen_screen_destroy(void)
{
    if(ui_HelpScreen) lv_obj_del(ui_HelpScreen);

    // NULL screen variables
    ui_HelpScreen = NULL;

}
