// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: TFT160x128

#ifndef UI_HELPSCREEN_H
#define UI_HELPSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HelpScreen
extern void ui_HelpScreen_screen_init(void);
extern void ui_HelpScreen_screen_destroy(void);
extern lv_obj_t * ui_HelpScreen;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

