// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: TFT160x128

#include "ui.h"

lv_obj_t * uic_ConversionList;
lv_obj_t * uic_InputIDtextarea;
lv_obj_t * uic_CheckButton;
lv_obj_t * ui_MessScreen = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_CheckButton = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_InputIDtextarea = NULL;
lv_obj_t * ui_ConversionList = NULL;
lv_obj_t * ui_Conversation = NULL;
/*lv_obj_t * ui_Conversation[20] = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                                        NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL};*/
// event funtions
void ui_event_CheckButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CheckIDinDB(e);
    }
}

void ui_event_Conversation_Conversation(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ConversationScreen, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_ConversationScreen_screen_init);
    }
}

#define MAX_CONVERSATIONS 10
char *conversation_ids[MAX_CONVERSATIONS] = {0};  // lưu ID
int conversation_count = 0;
void CheckIDinDB(lv_event_t * e) {
    lv_textarea_t * textarea = (lv_textarea_t *)ui_InputIDtextarea;
    const char * id = lv_textarea_get_text(textarea);

    if (conversation_count < MAX_CONVERSATIONS) {
        conversation_ids[conversation_count++] = strdup(id);  // lưu ID
        lv_obj_t * conversation = ui_Conversation_create(ui_ConversionList);
        lv_obj_set_x(conversation, 0);
        lv_obj_set_y(conversation, lv_pct(-10));
        ui_Conversation[conversation_count - 1] = conversation; // lưu đối tượng Conversation
    }
}

void ui_MessScreen_screen_destroy(void)
{
    for(int i = 0; i < MAX_CONVERSATIONS; i++) {
        if(ui_Conversation[i] != NULL) {
            lv_obj_del(ui_Conversation[i]);
            ui_Conversation[i] = NULL;
        }
    }
    lv_obj_del(ui_MessScreen);
    ui_MessScreen = NULL;
    lv_obj_del(ui_Panel1);
    ui_Panel1 = NULL;
    lv_obj_del(ui_CheckButton);
    ui_CheckButton = NULL;
    lv_obj_del(ui_Label1);
    ui_Label1 = NULL;
    lv_obj_del(ui_Label2);
    ui_Label2 = NULL;
    lv_obj_del(ui_InputIDtextarea);
    ui_InputIDtextarea = NULL;
    lv_obj_del(ui_ConversionList);
    ui_ConversionList = NULL;
    for(int i = 0; i < MAX_CONVERSATIONS; i++) {
        if(ui_Conversation[i] != NULL) {
            lv_obj_del(ui_Conversation[i]);
            ui_Conversation[i] = NULL;
        }
    }
    // Free allocated memory for conversation IDs
    for(int i = 0; i < conversation_count; i++) {
        free(conversation_ids[i]);
        conversation_ids[i] = NULL;
    }
    conversation_count = 0; // Reset count
}
    lv_obj_set_style_bg_grad_color(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Button3, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_Button3);
    lv_img_set_src(ui_Image4, &ui_img_help_24dp_000000_fill0_wght300_grad0_opsz24_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, 0);
    lv_obj_set_y(ui_Image4, 2);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}   




// build funtions

void ui_MessScreen_screen_init(void)
{
    ui_MessScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MessScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_grad_color(ui_MessScreen, lv_color_hex(0x8BEAE6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_MessScreen, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_MessScreen);
    lv_obj_set_width(ui_Panel1, 158);
    lv_obj_set_height(ui_Panel1, 28);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, -49);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xD8D1D1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel1, lv_color_hex(0x2BC3AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel1, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x1C4AB9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CheckButton = lv_btn_create(ui_Panel1);
    lv_obj_set_width(ui_CheckButton, 40);
    lv_obj_set_height(ui_CheckButton, 20);
    lv_obj_set_y(ui_CheckButton, 0);
    lv_obj_set_x(ui_CheckButton, lv_pct(44));
    lv_obj_set_align(ui_CheckButton, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_CheckButton, LV_STATE_PRESSED);       /// States
    lv_obj_add_flag(ui_CheckButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CheckButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CheckButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CheckButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_CheckButton, lv_color_hex(0x09B6D0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_CheckButton, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_CheckButton, lv_color_hex(0x06FD48), LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label1 = lv_label_create(ui_CheckButton);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Check");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label1, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -53);
    lv_obj_set_y(ui_Label2, 0);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Enter ID");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InputIDtextarea = lv_textarea_create(ui_Panel1);
    lv_obj_set_width(ui_InputIDtextarea, lv_pct(50));
    lv_obj_set_height(ui_InputIDtextarea, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_align(ui_InputIDtextarea, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_InputIDtextarea, 54);
    lv_textarea_set_placeholder_text(ui_InputIDtextarea, "ID here");
    lv_textarea_set_one_line(ui_InputIDtextarea, true);
    lv_obj_set_style_text_color(ui_InputIDtextarea, lv_color_hex(0x060606), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_InputIDtextarea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_InputIDtextarea, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConversionList = lv_obj_create(ui_MessScreen);
    lv_obj_set_width(ui_ConversionList, lv_pct(100));
    lv_obj_set_height(ui_ConversionList, lv_pct(74));
    lv_obj_set_x(ui_ConversionList, 0);
    lv_obj_set_y(ui_ConversionList, lv_pct(12));
    lv_obj_set_align(ui_ConversionList, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ConversionList, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_ConversionList, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_add_state(ui_ConversionList, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_ConversionList, LV_OBJ_FLAG_SCROLL_WITH_ARROW);     /// Flags
    lv_obj_set_style_bg_grad_color(ui_ConversionList, lv_color_hex(0x73EADE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ConversionList, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_ConversionList, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Conversation = ui_Conversation_create(ui_ConversionList);
    lv_obj_set_x(ui_Conversation, 0);
    lv_obj_set_y(ui_Conversation, lv_pct(-10));

    ui_Conversation2 = ui_Conversation_create(ui_ConversionList);
    lv_obj_set_x(ui_Conversation2, 0);
    lv_obj_set_y(ui_Conversation2, lv_pct(-10));

    lv_obj_add_event_cb(ui_CheckButton, ui_event_CheckButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Conversation, ui_event_Conversation_Conversation, LV_EVENT_ALL, NULL);
    uic_CheckButton = ui_CheckButton;
    uic_InputIDtextarea = ui_InputIDtextarea;
    uic_ConversionList = ui_ConversionList;

}

void ui_MessScreen_screen_destroy(void)
{
    if(ui_MessScreen) lv_obj_del(ui_MessScreen);

    // NULL screen variables
    ui_MessScreen = NULL;
    ui_Panel1 = NULL;
    uic_CheckButton = NULL;
    ui_CheckButton = NULL;
    ui_Label1 = NULL;
    ui_Label2 = NULL;
    uic_InputIDtextarea = NULL;
    ui_InputIDtextarea = NULL;
    uic_ConversionList = NULL;
    ui_ConversionList = NULL;
    ui_Conversation = NULL;

}
