// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: TFT160x128

#ifndef UI_MESSSCREEN_H
#define UI_MESSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MessScreen
extern void ui_MessScreen_screen_init(void);
extern void ui_MessScreen_screen_destroy(void);
extern lv_obj_t * ui_MessScreen;
extern lv_obj_t * ui_Panel1;
extern void ui_event_CheckButton(lv_event_t * e);
extern lv_obj_t * ui_CheckButton;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_InputIDtextarea;
extern lv_obj_t * ui_ConversionList;
extern void ui_event_Conversation_Conversation(lv_event_t * e);
extern lv_obj_t * ui_Conversation;
extern void ui_event_Conversation2_Conversation(lv_event_t * e);
extern lv_obj_t * ui_Conversation2;
extern void ui_event_Conversation3_Conversation(lv_event_t * e);
extern lv_obj_t * ui_Conversation3;
extern void ui_event_Conversation4_Conversation(lv_event_t * e);
extern lv_obj_t * ui_Conversation4;
extern void ui_event_Conversation5_Conversation(lv_event_t * e);
extern lv_obj_t * ui_Conversation5;
extern void ui_event_Conversation6_Conversation(lv_event_t * e);
extern lv_obj_t * ui_Conversation6;
extern void ui_event_Conversation7_Conversation(lv_event_t * e);
extern lv_obj_t * ui_Conversation7;
// CUSTOM VARIABLES
extern lv_obj_t * uic_CheckButton;
extern lv_obj_t * uic_InputIDtextarea;
extern lv_obj_t * uic_ConversionList;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

